[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "structlog>=25.3.0",
]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
]
